[  feat  ] Header 레이아웃 구현
nori-dongsan/nori-client pull request #14
Opened 2022-07-09 09:49 UTC by Brokyeom

## 🔥 Related Issues
- close #3 

## 🎡 작업 내용
- [x] ~ Header 컴포넌트 레이아웃 구성
- [x] ~ 로고, 상품보기, 커뮤니티 버튼에 Link 적용

## ✅ PR Point
- 헤더 컴포넌트 구현 완료했습니다.
- 어제 나온 input 관련해서 수정하느라 PR 이 늦었습니다.
- StTopLink, ABOUT 부분은 아직 페이지가 만들어지지않아 일단 텍스트로 두었습니다!

## 😡 Trouble Shooting
밑 스크린샷 보면 GlobalStyle 로 폰트가 지정되어 있을텐데,
 pretandard 로 폰트를 지정해준 placeholder를 제외하고 폰트가 적용되지 않는 모습을 보입니다. PR 올린 후에 develop 에서 수정된 부분 확인해보겠습니다.

PR 올린 후 스타일 초기 세팅대로 수정토록 하겠습니다!

## 👀 스크린샷 / GIF / 링크
![기본](https://user-images.githubusercontent.com/97586683/178100632-d7038f7f-2c93-485e-ac2a-dd3d9071d621.png)

input에 focus 되었을 때

![input 커서](https://user-images.githubusercontent.com/97586683/178100659-164074df-296c-4a3b-bf2b-e358767f2b18.png)

2022-07-09 10:23 UTC, aeuna requested changes
굳굳 수고하셨습니당
스타일 세팅된 거 적용만 시키면 끝이네용 굳굳 👍

2022-07-09 10:23 UTC, aeuna commented on components/common/Header.tsx
> +            <StMenuBtn type="button" onClick={() => router.push('/community')}>
#1 이슈보면 하단 리뷰에 
링크 이동은 next js 에서 제공하는 Link 태그가 더 SEO에 최적화된다고 알고 있습니다 !!
라는 리뷰가 있어요! 그래서, 새탭열지 않고 우리 페이지들 중에서 링크 전환하는 거면 Link태그 사용하면 좋을 것 같습니다!

2022-07-09 10:23 UTC, aeuna commented on components/common/Header.tsx
> +            <input placeholder="상품명, 스토어명을 검색해보세요!" />
input type도 적어주면 좋을 것 같아용

2022-07-09 10:23 UTC, aeuna commented on components/common/Header.tsx
> +
우리 컨벤션에서 스타일드 컴포넌트 사이에는 띄어쓰기 안 하는걸로 했어용!

2022-07-09 10:42 UTC, Brokyeom commented on components/common/Header.tsx
> +            <StMenuBtn type="button" onClick={() => router.push('/community')}>
아아 맞다맞다 바로 수정할게유

2022-07-09 10:42 UTC, Brokyeom commented on components/common/Header.tsx
> +
확인! 바로 수정할게!!

2022-07-09 23:28 UTC, Happhee reviewed
야물딱지게 잘했넹 ㅎㅎㅎㅎ 져아

2022-07-09 23:28 UTC, Happhee commented on components/common/Header.tsx
> +        <IcNoriHeaderLogo type="button" onClick={() => router.push('/')} />
Svg에도 타입을 지정해줘야 하나,,,?!!

2022-07-10 19:03 UTC, say-young516 commented
뀻~~~ 이래저래 정신없을텐데 고생했어욥 리뷰 달려고 보니까 다른 친구들이 야무지게 달아줬네 굿굿

2022-07-11 02:25 UTC, Brokyeom commented on components/common/Header.tsx
> +        <IcNoriHeaderLogo type="button" onClick={() => router.push('/')} />
음 일단은 버튼 기능을 해서 지정은 해 뒀는데 굳이 할 필요 없으려나??

2022-07-11 12:16 UTC, merged