[ Header ]  write 컴포넌트용 header 구현
nori-dongsan/nori-client pull request #45
Opened 2022-07-14 17:15 UTC by Brokyeom

## 🔥 Related Issues
- close #44 

## 🎡 작업 내용
- [x] ~ 기능 구현
- [x] ~ 페이지 구조화 및 스타일링

## ✅ PR Point
- 컴포넌트의 pathname === write 인 경우에 header 를 <WriteHeader /> 로 출력되도록 했습니다.

## 👀 스크린샷 / GIF / 링크
![writeheader](https://user-images.githubusercontent.com/97586683/179043585-fd787688-4313-46b6-8522-a4a76afc72ec.png)

2022-07-15 12:59 UTC, say-young516 commented
수고했어요~ 레이아웃 같은 건 머지하고 망가지는 데 없는지 살펴볼게요~

2022-07-16 04:37 UTC, aeuna requested changes
굳굳 수고하셨습니다! 
수정한 파일만 딱 올라올 수 있도록 브랜치 합치기 전에 최신 상태로 반영해주고 pr 날려주시면 더 좋을 것 같습니다!

2022-07-16 04:37 UTC, aeuna commented on components/common/WriteHeader.tsx
> +const StWriteHeaderWrapper = styled.section`
헤더니까 section 태그 말고 header 태그를 써주면 더 좋을 것 같아요!

2022-07-16 12:30 UTC, Happhee commented
수고해따 시루 ㅎㅎ

2022-07-17 16:31 UTC, merged