[ Main ] 상품 노출 미리보기 컴포넌트 만들기
nori-dongsan/nori-client pull request #6
Opened 2022-07-07 16:35 UTC by Happhee

## 🔥 Related Issues
- close #2 

## 🎡 작업 내용
- [x] common -> ToyPreview.tsx
- [x] 정렬하는 css 공부하기
- [x] 영이에게 전달하기

## ✅ PR Point
- `display : flex `와 `position : relative, absolute` 사용해서 정렬 구현하였습니당✨
- 알고보니 관심과목마크 크기가 테두리 >> 색칠 이었어서 굳이 props로 넘겨서 배경바꾸는 것보다 고냥 css사용해서
토글로 보여주기만 하면뎀!!

## 😡 Trouble Shooting
<img width="588" alt="스크린샷 2022-07-07 오후 9 10 49" src="https://user-images.githubusercontent.com/79238676/177824439-c57642bd-4997-4334-9ecf-bcd9680507b1.png">
props를 올바르게 전달하지 못하고 있는데,,,! 

`const StToyMarkprop = styled(({ isMark, ...props }) => ( <IcToyMark {...props} /> ))`로 해결을 하려고 했으나 아직 도전중 ㅠㅠ

## 👀 스크린샷 / GIF / 링크
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/79238676/177824492-af630466-c495-438d-9149-e9883abdcedb.png">

## 📚 Reference
- [[React.js / Typescript] styled-components에서 변수 사용하기
](https://defineall.tistory.com/951)

2022-07-08 05:42 UTC, aeuna requested changes
깔끔하게 후다닥 잘 작업했네 👍 
아 저 트러블 슈팅 이슈! 무조건 나올 것 같은데,, 뭐가 문제 일지 증말 ㅠ
컨벤션 의논한거 적용시키고, 디자인 확정되면 그대로 fix해도 될 것 같아용

2022-07-08 05:42 UTC, aeuna commented on components/main/MainBanner.tsx
> +const StMainBannerWrapper = styled.header`
이 큰 배너가 페이지 내릴 때, 같이 내려가는 형식이 아니라면 태그가 header보다는 div or aside가 낮지 않을까 싶습니다!

[ aside ]
본문 전체 내용과 직접적인 연관성이 없는 분리된 내용을 담을 때 사용.
Ex) 사이드바에 사용되며, 배너 광고, 위젯등이 있다.

2022-07-08 05:42 UTC, aeuna commented on pages/main.tsx
> +          <ToyList />
ToyList가 메인페이지에서만 쓰이면 main 폴더에 있는게 맞지 않을까 싶습니다!
이번주 인기 장난감이랑 다른 섹션에서 나타나는 리스트안에서 상품 사이들의 간격이나 크기가 생각보다 달라서 공통 컴포넌트로 빼기가 애매하지 않을까 생각이 들었습니당 props를 받아서 공통적으로 사용할거면 common에 있어도 될 것 같습니다!!

2022-07-08 10:35 UTC, Happhee commented on components/main/MainBanner.tsx
> +const StMainBannerWrapper = styled.header`
아하!! 조은 의견이다!! aside로 빼는게맞는것같아용 ㅎㅎ

2022-07-08 10:36 UTC, Happhee commented on pages/main.tsx
> +          <ToyList />
상품보기 쪽에서도 활용할 생각입니다! grid 규격이나 배치도 다 props로 받을 생각입니다!

2022-07-08 11:19 UTC, say-young516 commented
아 영이한테 전달하기 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ개웃기네 ㅠㅠ

2022-07-08 11:22 UTC, say-young516 commented on components/common/ToyPreview.tsx
> +  }
요거는 {price}원 이라구 태그 안에 안 넣구 여기에 따로 뺀 이유가 있나?? 궁금행!

2022-07-08 11:23 UTC, say-young516 commented on components/common/ToyPreview.tsx
> +}
아 말해뭐해~ 넘 깔끔해서 속이 다 편안한 코드~ 굿입니다

2022-07-08 16:45 UTC, Happhee commented on components/common/ToyPreview.tsx
> +  }
price가 지금 숫자여서 ,요거 넣고 빼고 하는데 '원'이 방해될것같아서!!

2022-07-09 05:25 UTC, aeuna approved these changes

2022-07-11 12:08 UTC, merged